NAME = libft.a

SRCS = ft_atoi.c       ft_isprint.c    ft_putchar_fd.c ft_striteri.c   ft_strnstr.c \
ft_bzero.c      ft_itoa.c       ft_putendl_fd.c ft_strjoin.c    ft_strrchr.c \
ft_calloc.c     ft_memchr.c     ft_putnbr_fd.c  ft_strlcat.c    ft_strtrim.c \
ft_isalnum.c    ft_memcmp.c     ft_putstr_fd.c  ft_strlcpy.c    ft_substr.c \
ft_isalpha.c    ft_memcpy.c     ft_split.c      ft_strlen_lib.c     ft_tolower.c \
ft_isascii.c    ft_memmove.c    ft_strchr.c     ft_strmapi.c    ft_toupper.c \
ft_isdigit.c    ft_memset.c     ft_strdup.c     ft_strncmp.c   


OBJS = $(SRCS:.c=.o)


FLAGS = -Wall -Wextra -Werror

HEADER = libft.h

all: $(NAME)

$(NAME): $(HEADER) $(SRCS)
	gcc $(FLAGS) -c $(SRCS)
	ar -rsc $(NAME) $(OBJS)

bonus: $(HEADER) 
	gcc $(FLAGS) -c
	ar -rsc $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
